events {
  worker_connections 1024;
}

error_log /dev/stderr info;

http {
  access_log /dev/stdout;

  # Modified tutorial's loadbalancer container to route
  # regional load by fake region as input.
  map $http_x_viewer_region $edge_pool {
    west    edge_west_pool;
    east    edge_east_pool;
    default edge_east_pool; # Default to east cause Georgia.
  }

  # Separate tutorial's upstream hash consistency by region.
  upstream edge_west_pool {
    hash   $uri consistent;
    server edge-west-0:8080;
    server edge-west-1:8080;
  }

  upstream edge_east_pool {
    hash   $uri consistent;
    server edge-east-0:8080;
    server edge-east-1:8080;
  }

  server {
    listen 8080;

    location / {
      proxy_pass http://$edge_pool;
      proxy_http_version 1.1;
      proxy_set_header Connection "";

      add_header X-LB-Strategy viewer-region always;
      add_header X-Upstream-Addr $upstream_addr always;
      add_header X-Viewer-Region $http_x_viewer_region always; # Add response header.
    }
  }
}
