events {
  worker_connections 1024;
}

error_log /dev/stderr info;

http {
  access_log /dev/stdout;
  lua_package_path "/etc/nginx/lua/?.lua;;";

  server {
    listen 8080;
    add_header X-Origin-Server $hostname always;

    location / {
      content_by_lua_block {
        local origin = require "origin"
        origin.respond()
      }
    }
  }
}
